M48
; DRILL file {KiCad 9.0.6} date 2026-05-15T16:06:42+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T16:06:42+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-130.0
X160.0Y-5.0
X160.0Y-130.0
M30
