M48
; DRILL file {KiCad 9.0.6} date 2026-05-15T15:59:47+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T15:59:47+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X57.989Y-5.7
X62.839Y-5.7
T2
X57.689Y-2.67
X63.139Y-2.67
M30
